name: Compile snake.java

on:
  push:
    branches: master # Compile on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu as the build environment
    
    steps:
    - name: Checkout code # Checkout your repository code
      uses: actions/checkout@v2

    - name: Set up Java # Set up Java development environment
      uses: actions/setup-java@v1
      with:
        java-version: '11' # Set the Java version to use for the build

    - name: Build snake.java # Build snake.java file
      run: javac snake.java
      
    - name: Generate .exe # Generate executable file
      run: gcj -o snake.exe snake.java
