name: Build Executables

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build JAR
        run: javac Snake.java && jar cvfm Snake.jar MANIFEST.MF Snake.class

      - name: Download and cache Electron
        uses: actions/cache@v2
        with:
          path: ~/.cache/electron
          key: electron-cache
          restore-keys: |
            ${{ runner.os }}-electron-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Build Windows Executable
        uses: electron-userland/electron-builder-action@v1
        with:
          platform: windows
          config: ./electron-builder.yml

      - name: Build Linux Executable
        uses: electron-userland/electron-builder-action@v1
        with:
          platform: linux
          config: ./electron-builder.yml

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
