name: Build Executables

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Create MANIFEST.MF
        run: echo "Main-Class: Snake" > MANIFEST.MF

      - name: Build JAR
        run: javac Snake.java && jar cvfm Snake.jar MANIFEST.MF Snake.class

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Electron Builder
        run: npm install electron-builder@22.11.7

      - name: Build Windows Executable
        run: npx electron-builder build --windows

      - name: Build Linux Executable
        run: npx electron-builder build --linux

      - name: Build macOS Executable
        run: npx electron-builder build --macos

      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
